### ISSUE TITLE
Kronecker Product

### ISSUE THREAD

**Issue by ciallen** [James-Thorson/2018_FSH556#16]
Hi Jim,

Can you please post the updated notation for the Kronecker product from Week 6 lecture?

Thanks!

**Comment by James-Thorson** [comment]
OK, I'm posting an updated version that updates slides 8, 10, 11, and 13

**Comment by ciallen** [comment]
Thanks!


*C. Allen Akselrud*, MSc
NMFS-Sea Grant Fellow
School of Aquatic and Fishery Sciences
University of Washington

Email: cia2@uw.edu
