### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by ciallen** [James-Thorson/2018_FSH556#21]
I can run MakeADFun without error, but when I try to optimize, I get an error:

Error in solve.default(h, g) : 
  Lapack routine dgesv: system is exactly singular: U[3,3] = 0

Does anyone know what this error message means??

**Comment by jkbest2** [comment]
Usually you have a parameter that isn't contributing to the log-likelihood. I'd recommend looking at the 3rd parameter and seeing how it's involved.

**Comment by James-Thorson** [comment]
Please see [issue 18](https://github.com/James-Thorson/2018_FSH556/issues/18) for a description of the primary ways that a TMB model will fail and how to interpret them.  Please tell me if you'd like me to flesh out that doc a bit.
