### ISSUE TITLE
EBS_pollock_data not found

### ISSUE THREAD

**Issue by tXiao95** [James-Thorson/2018_FSH556#22]
Hi James! Thanks for putting all of this online. 

I have TMB, INLA, and the stable 3.3 version of `SpatialDeltaGLMM` installed and was working through HW1 but couldn't locate the `EBS_pollock_data`. The only datasets in the package are `WCGBTS_Canary_example` and `extrapolation_data`. Do you know where I can find it?

**Comment by James-Thorson-NOAA** [comment]
Please try `FishStatsUtils` instead; that's where I have moved all dependencies and data sets from `SpatialDeltaGLMM`

**Comment by tXiao95** [comment]
Got it! Thanks
