### ISSUE TITLE
Map argument turning on and off random effects

### ISSUE THREAD

**Issue by klomori** [James-Thorson/2018_FSH556#5]
In the example Map Argument file that was uploaded to GitHub, I can run the model with the Map function (turning off the random effects, Z and log_SDZ), but am still getting results from log_SDZ. How is this possible?

**Comment by James-Thorson** [comment]
Kristin,

Could you email me your code?  

Short answer:  you've got some bug in how you're defining `Map` in `MakeADFun( ..., map=Map )`.

Jim

**Comment by James-Thorson** [comment]
OK, thanks for clarifying my email, I think I understand your question better.  Let's discuss in class today, I'll spend a portion of lab going over the `map` input.
