### ISSUE TITLE
HW 3 forecast interval clarification

### ISSUE THREAD

**Issue by klomori** [James-Thorson/2018_FSH556#9]
To calculate the 50% forecast interval, do you mean 50% confidence interval or 50% +/- of the parameter estimate?

**Comment by James-Thorson** [comment]
I mean the 50% forecast interval for prediction for state x_tp, which should incorporate uncertainty about fixed effects and random effects.  This is what was done in the Week 4 lab code when generating forecast intervals for years 101-120.
